[package]
name = "aoc_2024"

[[bin]]
name="aoc_2024"
path="src/main.rs"

[dependencies]
day_1 = {path = "src/1"}
day_2 = {path = "src/2"}
day_3 = {path = "src/3"}
day_4 = {path = "src/day_4"}
day_5 = {path = "src/day_5"}